[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/home/sohaib/.config/quickshell/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
#output_path = "/home/sohaib/.cache/noctalia/placeholder.json"

[templates.asus_keyboard]
input_path = "~/.config/noctalia/templates/asus-kbd.json"
output_path = "~/.cache/noctalia/kbd_wallpaper.json"
post_hook = "/usr/bin/bash -lc \"$HOME/.local/bin/noctalia-asus-kbd-smart\""
