include ./nord.conf

# Transparency (0.0 = fully transparent, 1.0 = solid)
background_opacity 0.5
dynamic_background_opacity yes

# Nice spacing
window_padding_width 8

# Coding enhancements
font_family Fira Code
scrollback_lines 5000
copy_on_select yes
enable_audio_bell no

# Keybindings for coding
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+f kitten hints --type path --program -

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME