include ./nord.conf

# Transparency (0.0 = fully transparent, 1.0 = solid)
background_opacity 0.85
dynamic_background_opacity yes

# Nice spacing
window_padding_width 8


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME