input {
  kb_layout = fr
  kb_variant =
  kb_options =
}


# ---------- INPUT / TOUCHPAD ----------
input {
  touchpad {
    natural_scroll = true
  }
}

# ---------- 3-finger workspace swipe ----------
# GNOME-like: swipe left/right to change workspace
gesture = 3, horizontal, workspace

# ---------- MONITOR SCALE (make UI smaller) ----------
# 1 = unscaled. If it was 1.25 / 1.5 before, this will make things smaller.
monitor = ,preferred,auto,1.2



# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 0
    layout = dwindle
    resize_on_border = true
}


# -----------------------------------------------------
# General window decoration
# name: "Rounding All Blur No Shadows"
# -----------------------------------------------------

decoration {
    rounding = 0
   # active_opacity = 1.0
    inactive_opacity = 0.7
    # fullscreen_opacity = 1.0

    blur {
     enabled = true
     size = 8
     passes = 2
     new_optimizations = true
     ignore_opacity = true
   }

    # shadow {
        # enabled = true
       #  range = 32
      #   render_power = 2
     #    color = rgba(00000050)
    # }
}