# Polkit agent (Fedora 43 / KDE agent)
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1

# Notifications
exec-once = mako

# Noctalia shell (Quickshell)
exec-once = qs -c noctalia-shell



# Clipboard history backend (text + images)
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store



env = QT_QPA_PLATFORMTHEME,qt6ct